import { ioc } from "anyioc";

import { AppOptions } from "../options";
import { InfoBuilder } from "../doggoo";

ioc.registerSingleton('info-builder', () => {
    const options = ioc.getRequired<AppOptions>('options');
    const appinfo = ioc.getRequired<any>('app-info');

    const builder: InfoBuilder = {
        appinfo: `${appinfo.name} (build ${appinfo.build})`,
        source: options.source || '',
        format: 'file',
        toString: function () {
            return `This ${this.format} was generated by ${this.appinfo} from ${this.source}`;
        }
    };

    return builder;
});
