'use strict';

const { ioc } = require('@adonisjs/fold');

const { Novel } = require('../models/novel');

class SessionContext {
    constructor() {
        const options = ioc.use('options');
        this.src = null;
        Object.defineProperties(this, {
            _middlewares: {
                value: []
            },
            env: {
                value: {}
            },
            novel: {
                value: new Novel()
            },
            appopt: {
                value: options
            }
        });
    }

    get novel() {
        return this._novel;
    }

    getGenerateMessage(format) {
        const appinfo = ioc.use('app-info');
        const src = this.src || this.appopt.source;
        return `This ${format} was generated by ${appinfo.name} (build ${appinfo.build}) from ${src}`;
    }

    addMiddleware(middleware) {
        this._middlewares.push(middleware);
    }

    async run() {
        for (const middleware of this._middlewares) {
            await middleware.run(this);
        }
    }
}

module.exports = SessionContext;
